
--Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender


--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount 
from customer 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT TOP 5 
item_purchased,
CAST(ROUND(AVG(review_rating * 1.0), 2) AS DECIMAL(10,2))-- Multiply by 1.0 to make sure SQL treats the value as decimal and gives a proper average.
AS [Average Product Rating]
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating * 1.0) DESC;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type,
cast(round(avg(purchase_amount *1.0), 2) as decimal(10,2)) as shipping_type_amount
from customer
where shipping_type in('Standard', 'Express')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
select subscription_status,
CAST(round(avg(purchase_amount *1.0),2) as decimal(10,2)) as avg_spend,
CAST(round(sum(purchase_amount *1.0),2) as decimal(10,2)) as total_revenue,
count(customer_id) as total_customers
from customer
group by subscription_status
order by total_revenue,avg_spend desc;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select top 5 item_purchased,
cast(
--Counts how many times discount was used per product.
(sum(case when discount_applied ='Yes' then 1 else 0 end)*100.0/count(*)) as decimal(5,2)) as discount_percentage
from customer
group by item_purchased
order by discount_percentage desc;


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
select customer_segment,
count(*) as total_customers
from(
select
case 
when previous_purchases = 0 then 'New'
when previous_purchases between 1 and 5 then 'Returning'
else 'Loyal'
end as customer_segment
from customer) as segmented
group by customer_segment
order by total_customers desc;

--Q8. What are the top 3 most purchased products within each category? 
SELECT category,
       item_purchased,
       total_purchases
FROM (
    SELECT category,
           item_purchased,
           COUNT(*) AS total_purchases,
           ROW_NUMBER() OVER (
               PARTITION BY category 
               ORDER BY COUNT(*) DESC
           ) AS rn
    FROM customer
    GROUP BY category, item_purchased
) AS ranked_products
WHERE rn = 3
ORDER BY category, total_purchases DESC;
 
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;
--Q11. Which shipping type generates highest total revenue? 

select top 1 shipping_type,
cast(sum(purchase_amount * 1.0) as decimal(10,2)) as total_revenue
from customer
group by shipping_type
order by total_revenue desc;

--Q12. What is the average purchase amount for subscribed vs non subscribed customers?

select subscription_status,
cast(avg(purchase_amount * 1.0) as decimal(10,2)) as average_spend
from customer
group by subscription_status;



